### ISSUE TITLE
rfcstrip fails on rfc8299 

### ISSUE THREAD

**Issue by carloperocchio** [mbj4668/rfcstrip#1]
The issue:
rfcstrip fails to extract yang module from rfc8299 due to imprecisions in module indentation. 
     rfc ~/8299 $ ./rfcstrip rfc8299.txt
     ietf-l3vpn-svc.yang: 289 `lines.`
the extracted module is truncated, as reported by the validation with pyang
    rfc ~/8299 $ pyang --lint --ietf ietf-l3vpn-svc.yang
    ietf-l3vpn-svc.yang:289: error: premature end of file

Honestly I don't know if the issue is in refstrip or in the rfc.

A note to the issue:
In the meanwhile I've tried some changes to rfcstrip to get yang module in rfc, here is the result and a patch that illustrates changes.
I don't know if changes are suitable for any case that rfcstrip must support.

`rfc ~/8299 $ ./rfcstrip-mod rfc8299.txt
SUSPECT END with no match with at line 289, looking forward in ietf-l3vpn-svc
SUSPECT END with no match with at line 575, looking forward in ietf-l3vpn-svc
SUSPECT END with no match with at line 580, looking forward in ietf-l3vpn-svc
SUSPECT END with no match with at line 1910, looking forward in ietf-l3vpn-svc
SUSPECT END with no match with at line 1928, looking forward in ietf-l3vpn-svc
SUSPECT END with no match with at line 2857, looking forward in ietf-l3vpn-svc
ietf-l3vpn-svc.yang: 2857 lines.

rfc ~/8299 $ pyang --lint --ietf ietf-l3vpn-svc.yang

rfc ~/8299 $ diff -Naur rfcstrip rfcstrip-mod
--- rfcstrip    2018-06-29 12:07:49.682541700 +0200
+++ rfcstrip-mod        2018-06-29 15:03:19.268174700 +0200
@@ -156,7 +156,7 @@
     }

     # generic end marker
-    type == 1 && /^[ \t]*<CODE ENDS>.*$/ {
+    ((type == 1)||( type == 3 )) && /^[ \t]*<CODE ENDS>.*$/ {
         if ((length(single) == 0) || (single == file)) {
             n--
             strip = 99
@@ -242,37 +242,7 @@
     type == 3 && /^[ \t]*}.*$/ {
         indent = match($0, "[^ \t]")
         if (indent == modindent) {
-            modindent = -1
-            # we assume that a module is ended with a single "}" with the
-            # same indentation level as the module statement.
-            if ((length(single) == 0) || (single == module)) {
-                strip = 99
-                for (i=0 ; i < n ; i++) {
-                    # find the minimum column that contains non-blank characters
-                    # in order to cut a blank prefix off. Ignore lines that only
-                    # contain white spaces.
-                    if (!(line[i] ~ /^[ \t]*$/)) {
-                        p = match(line[i], "[^ ]")
-                        if ((p < strip) && (length(line[i]) > p)) { strip = p }
-                    }
-                }
-
-                if (test != "1") {
-                    if (dir) {
-                       f = dir"/"file
-                    } else {
-                       f = file
-                    }
-                    for (i=0 ; i < n ; i++) {
-                        print substr(line[i], strip) >f
-                    }
-                }
-
-                print f ": " n " lines."
-            }
-            module = ""
-            file = ""
-            type = 0
+            print "SUSPECT END with no match with at line " n ", looking forward in " module
         }
     }

`

**Comment by sunseawq** [comment]
It is your tool issue, why not try pyang instead? pyang has been integrated into IETF datastracker which will help extract YANG data model and check compilation results.

**Comment by carloperocchio** [comment]
Unfortunately as of now 'rfcstrip' is recommended by NETMOD wg within the 'Guidelines for Authors and Reviewers of YANG Data Model Documents'  available in 
https://tools.ietf.org/html/draft-ietf-netmod-rfc6087bis-20#section-3.11
"Module Extraction Tools", published in March this year.
Probably the draft should be updated with your proposal.
Have you already proposed the change?

**Comment by sunseawq** [comment]
Section 3.11 also said:

“
   The "xym" tool is freely available on github and can be used to
   extract YANG modules from a document.

      https://github.com/xym-tool/xym
”
Xym tool is what we usually use. Have integrated into datatracker, part of pyang tool.

-Qin
发件人: carloperocchio [mailto:notifications@github.com]
发送时间: 2018年7月16日 18:15
收件人: mbj4668/rfcstrip <rfcstrip@noreply.github.com>
抄送: Qin Wu <bill.wu@huawei.com>; Comment <comment@noreply.github.com>
主题: Re: [mbj4668/rfcstrip] rfcstrip fails on rfc8299 (#1)


Unfortunately as of now 'rfcstrip' is recommended by NETMOD wg within the 'Guidelines for Authors and Reviewers of YANG Data Model Documents' available in
https://tools.ietf.org/html/draft-ietf-netmod-rfc6087bis-20#section-3.11
"Module Extraction Tools", published in March this year.
Probably the draft should be updated with your proposal.
Have you already proposed the change?

**Comment by carloperocchio** [comment]
Yes, I know (I've referred to the best practices).
Is rfcstrip still supported as YANG tool? It looks like no. 
The best practices suggested by netmod will be amended, what do you think? 
(Indeed yang central too refers to an older version of rfcstrip)

**Comment by mbj4668** [comment]
The problem was that the RFC used <CODE BEGINS>file w/o any space between > and file.  I have now fixed rfcstrip so that it can handle this (erroneous) case as well.

rfcstrip is certainly supported and should work for all RFCs and I-Ds.

**Comment by carloperocchio** [comment]
Thanks Martin for your update and for still supporting rfcstrp.
I agree.
In my opinion ietf references to rfcscrip should be updated with github repo.
